"""

Stimulus animator: animate a stimulus by moving it

@author: Dror Dotan
@copyright: Copyright (c) 2017, Dror Dotan
"""

import numbers

import dobbyt
import dobbyt._utils as _u


class StimulusAnimator(dobbyt._DobbyObject):
    """
    Move a stimulus in a predefined visual trajectory.
    """


    def __init__(self, animated_object=None, trajectory_generator=None, position_shift=None):
        """
        Constructor

        :param animated_object: See :func:`dobbyt.movement.StimulusAnimator.animated_object`
        :type animated_object: Expyriment stimulus

        :param trajectory_generator: See :func:`dobbyt.movement.StimulusAnimator.trajectory_generator`

        :param position_shift: See :func:`dobbyt.movement.StimulusAnimator.position_shift`
        :type position_shift: tuple
        """
        super(StimulusAnimator, self).__init__()

        self.animated_object = animated_object
        self.trajectory_generator = trajectory_generator
        self.position_shift = position_shift
        self.do_clear_screen = False
        self.do_update_screen = False
        self.reset()


    #=======================================================================
    # Move
    #=======================================================================

    #------------------------------------------------------------
    def reset(self, time0=0):
        """
        Reset the movement. This does not move the object, it just resets the time

        :param time0: The time that counts as zero (when calling the position-generator)
        """
        self._time0 = time0


    #------------------------------------------------------------
    def update(self, time):
        """
        Call this function on each frame where you want the animated object to move.

        :param time: The time (typically - time from start of trial)
        """
        _u.validate_func_arg_type(self, "update", "time", time, numbers.Number)

        if self._animated_object is None or self._trajectory_generator is None:
            return

        relative_time = time - self._time0

        x, y = self._trajectory_generator.get_xy(relative_time)
        self._animated_object.position = x, y
        self._animated_object.present(update=self._do_update_screen, clear=self._do_clear_screen)


    #=======================================================================
    # Configure
    #=======================================================================

    #------------------------------------------------------------
    @property
    def animated_object(self):
        """
        The object being moved by this animator.
        The object should be an Expyriment visual stimulus - i.e., with a present(clear,update) method and a "position" property
        """
        return self._animated_object

    @animated_object.setter
    def animated_object(self, obj):
        if "present" not in dir(obj):
            raise ValueError("dobbyt error: {0}.animated_object must be an object with a present() method".format(type(self).__name__))
        if "position" not in dir(obj):
            raise ValueError("dobbyt error: {0}.animated_object must be an object with a 'position' property".format(type(self).__name__))

        self._animated_object = obj

    #------------------------------------------------------------
    @property
    def trajectory_generator(self):
        """
        An object that generates, per time point, the x,y coordinates where the animated object should be moved to
        """
        return self._trajectory_generator

    @trajectory_generator.setter
    def trajectory_generator(self, obj):

        if "get_xy" not in dir(obj):
            raise ValueError("dobbyt error: {0}.trajectory_generator must be an object with a get_xy() method".format(type(self).__name__))

        self._trajectory_generator = obj

    #------------------------------------------------------------
    @property
    def position_shift(self):
        """
        x,y coordinates. The coordinates generated by :func:`dobbyt.movement.StimulusAnimator.trajectory_generator` will be
        shifted by this amount before updating :func:`dobbyt.movement.StimulusAnimator.animated_object`

        This property can be set to x,y tuple/list or to an expyriment.geometry.XYPoint
        """
        return self._position_shift

    @position_shift.setter
    def position_shift(self, value):
        value = _u.validate_attr_is_coord(self, "position_shift", value)
        self._position_shift = value

    #------------------------------------------------------------
    @property
    def do_clear_screen(self):
        """
        If true, the screen will be cleared on each frame by calling animated_object.present(clear=True)
        """
        return self._do_clear_screen

    @do_clear_screen.setter
    def do_clear_screen(self, value):
        _u.validate_attr_type(self, "do_clear_screen", value, bool)
        self._do_clear_screen = value

    #------------------------------------------------------------
    @property
    def do_update_screen(self):
        """
        If true, the screen will be updated on each frame by calling animated_object.present(update=True)
        """
        return self._do_update_screen

    @do_update_screen.setter
    def do_update_screen(self, value):
        _u.validate_attr_type(self, "do_update_screen", value, bool)
        self._do_update_screen = value

